version: 2.1

executors:
  cpp-executor:
    docker:
      - image: ubuntu:22.04
    resource_class: small
    environment:
      CXX: g++
      CC: gcc

jobs:
  build-and-test:
    executor: cpp-executor
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            apt-get update && apt-get install -y curl zip unzip tar git cmake g++ pkg-config
            
      - run:
          name: Clone and Bootstrap vcpkg
          command: |
            git clone https://github.com/microsoft/vcpkg.git
            ./vcpkg/bootstrap-vcpkg.sh

      - run:
          name: Install GTest via vcpkg
          command: |
            ./vcpkg/vcpkg install gtest

      - run:
          name: Build Project with CMake and vcpkg
          command: |
            mkdir -p build
            cmake -Bbuild -S. -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake
            cmake --build build

      - run:
          name: Run Unit Tests
          command: |
            cd build
            GTEST_OUTPUT=xml:test-results.xml ctest --output-on-failure

      - run:
          name: Convert test results to JUnit format
          command: |
            mkdir -p build/test-results
            mv build/test-results.xml build/test-results/test-results.xml

      - store_test_results:
          path: build/test-results

      - store_artifacts:
          path: build/test-results
          destination: junit

workflows:
  version: 2
  test-and-coverage:
    jobs:
      - build-and-test
