version: 2.1

executors:
  cpp-executor:
    docker:
      - image: ubuntu:latest
    resource_class: small
    environment:
      VCPKG_ROOT: /opt/vcpkg

jobs:
  build-and-test:
    executor: cpp-executor
    steps:
      - checkout

      - run:
          name: Install Build Tools and vcpkg
          command: |
            apt-get update && apt-get install -y \
              curl zip unzip tar git cmake g++ make pkg-config

            git clone https://github.com/microsoft/vcpkg.git $VCPKG_ROOT
            $VCPKG_ROOT/bootstrap-vcpkg.sh

      - run:
          name: Install Dependencies via vcpkg
          command: |
            $VCPKG_ROOT/vcpkg install gtest cpr nlohmann-json

      - run:
          name: Clean build directory
          command: |
            rm -rf build && mkdir build

      - run:
          name: Build Project
          command: |
            cd build
            cmake .. -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake
            make

      - run:
          name: Run Unit Tests
          command: |
            cd build
            mkdir -p test-results
            ctest --output-on-failure --output-junit test-results/test-results.xml

      - store_test_results:
          path: build/test-results

      - store_artifacts:
          path: build/test-results
          destination: junit

workflows:
  version: 2
  test-and-coverage:
    jobs:
      - build-and-test