version: 2.1

executors:
  cpp_executor:
    docker:
      - image: gcc:latest
    working_directory: ~/project

jobs:
  build-and-test:
    executor: cpp_executor
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Required Packages
          command: |
            apt-get update
            apt-get install -y cmake ninja-build g++ make

      # Build Google Test
      - run:
          name: Install Google Test
          command: |
            cd /usr/local
            git clone https://github.com/google/googletest.git
            cd googletest
            mkdir build && cd build
            cmake ..
            make
            make install

      # Create a build directory and compile the project
      - run:
          name: Build the Project
          command: |
            mkdir -p build
            cd build
            cmake ..
            make

      # Run unit tests using CTest
      - run:
          name: Run Unit Tests
          command: |
            cd build
            ctest --output-on-failure

      # Store test results for CircleCI UI
      - store_test_results:
          path: build/test-results

workflows:
  version: 2
  test-and-build:
    jobs:
      - build-and-test

