version: 2.1

executors:
  cpp-executor:
    docker:
      - image: ubuntu:latest
    resource_class: small
    environment:
      CXX: g++
      CC: gcc
      VCPKG_ROOT: /opt/vcpkg

jobs:
  build-and-test:
    executor: cpp-executor
    steps:
      - checkout

      - run:
          name: Install Build Tools and vcpkg
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update && \
            apt-get install -y tzdata && \
            ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
            dpkg-reconfigure --frontend noninteractive tzdata && \
            apt-get install -y \
              clang-tidy \
              clang-format \
              curl zip unzip tar git cmake g++ make pkg-config \
              lcov

            git clone https://github.com/microsoft/vcpkg.git $VCPKG_ROOT
            $VCPKG_ROOT/bootstrap-vcpkg.sh

      - run:
          name: Install Dependencies via vcpkg
          command: |
            $VCPKG_ROOT/vcpkg install gtest cpr nlohmann-json

      - run:
          name: Clean build directory
          command: |
            rm -rf build && mkdir build

      - run:
          name: Build Project with Coverage
          command: |
            cd build
            cmake .. \
              -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
              -DCMAKE_CXX_FLAGS="--coverage"
            make

      - run:
          name: Run clang-tidy (Static Analysis)
          command: |
            clang-tidy include/*.h -- -Iinclude

      - run:
          name: Run clang-format check (Style Check)
          command: |
            clang-format --dry-run --Werror include/*.h tests/*.cpp

      - run:
          name: Run Unit Tests
          command: |
            cd build
            mkdir -p test-results
            ctest --output-on-failure --output-junit test-results/test-results.xml

      - run:
          name: Generate Code Coverage Report
          command: |
            cd build
            lcov --capture --directory . --output-file coverage.info --ignore-errors mismatch
            lcov --remove coverage.info '/usr/*' --output-file coverage.info
            genhtml --ignore-errors mismatch coverage.info --output-directory coverage-report

      - store_test_results:
          path: build/test-results

      - store_artifacts:
          path: build/test-results
          destination: junit

      - store_artifacts:
          path: build/coverage-report
          destination: coverage

workflows:
  version: 2
  test-and-coverage:
    jobs:
      - build-and-test
