version: 2.1

executors:
  cpp-executor:
    docker:
      - image: ubuntu:latest
    resource_class: small
    environment:
      CXX: g++
      CC: gcc

jobs:
  build-and-test:
    executor: cpp-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update && apt-get install -y cmake g++ git make
            apt-get install -y libgtest-dev
            cd /usr/src/googletest
            cmake . && make
            cp lib/*.a /usr/lib
      - run:
          name: Build Project
          command: |
            mkdir -p build
            cd build
            cmake ..
            make
      - run:
          name: Run Unit Tests
          command: |
            mkdir -p test-reports
            ./build/test_calculator > test-reports/calculator.xml
            ./build/test_logger > test-reports/logger.xml
            ./build/test_notifier > test-reports/notifier.xml

      - store_test_results:
          path: test-reports
      - run:
          name: Install Coverage Tools
          command: |
            sudo apt-get update
            sudo apt-get install -y lcov gcovr

      - run:
          name: Generate Test Coverage Report
          command: |
            gcovr -r . --xml -o test-reports/coverage.xml
            gcovr -r . --html --html-details -o test-reports/coverage.html

      - store_artifacts:
          path: test-reports/coverage.html
          destination: coverage-report
workflows:
  version: 2
  test-and-coverage:
    jobs:
      - build-and-test
