version: 2.1

executors:
  cpp-executor:
    docker:
      - image: ubuntu:latest
    resource_class: small
    environment:
      CXX: g++
      CC: gcc

jobs:
  build-and-test:
    executor: cpp-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update && apt-get install -y \
              cmake \
              g++ \
              git \
              make \
              libssl-dev \
              libcurl4-openssl-dev \
              libgtest-dev \
              nlohmann-json3-dev  # <--- this line is new

            # Build and install GoogleTest
            cd /usr/src/googletest
            cmake . && make
            cp lib/*.a /usr/lib

            # Clone and build CPR
            cd /tmp
            git clone --depth=1 https://github.com/libcpr/cpr.git
            cd cpr
            cmake -DCMAKE_BUILD_TYPE=Release -DCPR_USE_SYSTEM_CURL=ON .
            make -j$(nproc)
            make install
      - run:
          name: Build Project
          command: |
            mkdir -p build
            cd build
            cmake ..
            make
      - run:
          name: Run Unit Tests
          command: |
            cd build
            GTEST_OUTPUT=xml:test-results.xml ctest --output-on-failure
      - run:
          name: Convert test results to JUnit format
          command: |
            mkdir -p build/test-results
            mv build/test-results.xml build/test-results/test-results.xml

      - store_test_results:
          path: build/test-results  # Store test results for CircleCI UI

      - store_artifacts:
          path: build/test-results
          destination: junit  # Store test artifacts for later review

workflows:
  version: 2
  test-and-coverage:
    jobs:
      - build-and-test
