version: 2.1

executors:
  cpp-executor:
    docker:
      - image: ubuntu:latest
    resource_class: small
    environment:
      CXX: g++
      CC: gcc

jobs:
  build-and-test:
    executor: cpp-executor
    steps:
      - checkout

      - run:
          name: Install Dependencies (incl. CPR)
          command: |
            apt-get update && apt-get install -y \
              cmake \
              g++ \
              git \
              make \
              libssl-dev \
              libcurl4-openssl-dev \
              libgtest-dev \
              nlohmann-json3-dev

            cd /usr/src/googletest
            cmake . && make
            cp lib/*.a /usr/lib

            cd /tmp
            git clone https://github.com/libcpr/cpr.git
            cd cpr
            cmake -DCMAKE_USE_OPENSSL=ON .
            make -j$(nproc)
            make install

      - run:
          name: Build Project
          command: |
            rm -rf build
            mkdir build
            cd build
            cmake -DCMAKE_CXX_FLAGS="--coverage" ..
            make

      - run:
          name: Run Unit Tests
          command: |
            cd build
            GTEST_OUTPUT=xml:test-results.xml ctest --output-on-failure

      - run:
          name: Generate Code Coverage Report
          command: |
            cd build
            lcov --capture --directory . --output-file coverage.info --ignore-errors mismatch
            lcov --remove coverage.info '/usr/*' --output-file coverage.info
            genhtml --ignore-errors mismatch coverage.info --output-directory coverage-report

      - store_artifacts:
          path: build/coverage-report
          destination: coverage

workflows:
  version: 2
  test-and-coverage:
    jobs:
      - build-and-test
