version: 2.1

executors:
  cpp-executor:
    docker:
      - image: ubuntu:latest
    resource_class: small
    environment:
      CXX: g++
      CC: gcc

jobs:
  build-and-test:
    executor: cpp-executor
    steps:
      - checkout

      - run:
          name: Install Dependencies (incl. CPR)
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update && apt-get install -y \
              cmake \
              g++ \
              git \
              make \
              libgtest-dev \
              lcov \
              gcovr \
              libssl-dev \
              libcurl4-openssl-dev

            # Build and install GTest
            cd /usr/src/googletest
            cmake . && make
            cp lib/*.a /usr/lib

            # Install CPR from source
            cd /tmp
            git clone https://github.com/libcpr/cpr.git
            cd cpr
            cmake -DCMAKE_USE_OPENSSL=ON .
            make -j$(nproc)
            make install


      - run:
          name: Run Unit Tests
          command: |
            cd build
            GTEST_OUTPUT=xml:test-results.xml ctest --output-on-failure

      - run:
          name: Generate Code Coverage Report
          command: |
            cd build
            lcov --capture --directory . --output-file coverage.info --ignore-errors mismatch
            lcov --remove coverage.info '/usr/*' --output-file coverage.info
            genhtml --ignore-errors mismatch coverage.info --output-directory coverage-report

      - run:
          name: Convert test results to JUnit format
          command: |
            mkdir -p build/test-results
            [ -f build/test-results.xml ] && mv build/test-results.xml build/test-results/test-results.xml || true

      - store_test_results:
          path: build/test-results

      - store_artifacts:
          path: build/test-results
          destination: junit

      - store_artifacts:
          path: build/coverage.info
          destination: raw-coverage-data

      - store_artifacts:
          path: build/coverage-report
          destination: coverage

workflows:
  version: 2
  test-and-coverage:
    jobs:
      - build-and-test
